FROM node:18

# logged in as user "node"
USER node

# setup node environment
ENV NODE_ENV=development

# setup working directory
WORKDIR /home/node/app

# copy package.json to working directory
COPY --chown=node:node package.json ./

# install npm dependencies
RUN npm install && npm cache clean --force

# copy current directory to the container working directory
COPY --chown=node:node . .

# expose
EXPOSE 3000

# run startup command
CMD ["npm", "run", "dev"]